### ISSUE TITLE
my address is wrong

### ISSUE THREAD

**Issue by dehua666666** [FuelLabs/fuels-wallet#1108]
### What version of Wallet are you using?

fuel wallet

### What is happening?

i lost all my date. my address :fuel19cs49954qc5fwreaqcrysz0n5ktatdljzhzs4hy2cc5w4nrd0wdsxg78tt

### steps to reproduce

i just found everything was wrong

### How it should behave?

i play the sway farm but my date lost. i played for a month ...

### What os are you seeing the problem on?

Mac/Apple Desktop

### What browser?

Chrome

**Comment by cold-briu** [comment]
Hi there, as said by the bot, please consider requesting support directly on the forum.
 
I've just checked in [the explorer](https://fuel-explorer.vercel.app/account/0x2e215296950628970f3d06064809f3a597d5b7f215c50adc8ac628eacc6d7b9b/transactions) that your address `fuel19cs49954qc5fwreaqcrysz0n5ktatdljzhzs4hy2cc5w4nrd0wdsxg78tt` was created just 16 hours ago. 

Remember, the blockchain is immutable, and the sway farm data is stored on-chain, so it's impossible to lose data. The issue might be due to the creation of a new address instead of recovering your previous one.

You can continue accessing your farm if you have kept a copy of your seed phrase. Unfortunately, we're unable to recover your wallet for you.
