### ISSUE TITLE
When Wallet is not installed the docs should show a better message on the example sections

### ISSUE THREAD

**Issue by luizstacio** [FuelLabs/fuels-wallet#276]
When playing with the docs without having a wallet, the section should show a warning in each section and disable all the examples. Maybe an overlay with opacity over the code sample pointing to the install section on the docs.
<img width="926" alt="Screenshot 2022-11-29 at 13 02 29" src="https://user-images.githubusercontent.com/3941923/204647146-62696abc-a7f8-4b10-a78a-cbae82645738.png">

**Comment by tomiiide** [comment]
There is already a warning that tells the user that Fuel wallet was not detected, and provides a link to download it.

In #526 , I've disabled the `connect` button, when the wallet is not detected, so that error never occurs.



![Image](https://user-images.githubusercontent.com/15849997/217040430-568a43d5-0d1c-4b39-9d30-f10f294c6360.png)
![Image](https://user-images.githubusercontent.com/15849997/217040429-27ce6f3f-35e5-4e42-81eb-be313b7b6c2c.png)
