### ISSUE TITLE
no decrease in balance

### ISSUE THREAD

**Issue by aralper** [FuelLabs/fuels-wallet#623]
### What version of Wallet are you using?

Testnet Beta 3

### What is happening?

İn Thunder beta testnet probably has a wallet-related bug. I can buy unlimited ntf with 0.5 eth balance and the balance never decreases.
my adress: 0x64b9288e1e2d5e1d8506f3dca52cf8f1dd5c4836e5d069d7293c05ce2f76056c
fuel1vjuj3rs7940pmpgx70w22t8c78w4cjpkuhgxn4ef8szuutmkq4kq569mwq

### steps to reproduce

my adress: 0x64b9288e1e2d5e1d8506f3dca52cf8f1dd5c4836e5d069d7293c05ce2f76056c
fuel1vjuj3rs7940pmpgx70w22t8c78w4cjpkuhgxn4ef8szuutmkq4kq569mwq

### How it should behave?

When I make a transaction, the balance decreases :)

### What os are you seeing the problem on?

Windows Desktop

### What browser?

Chrome

**Comment by LuizAsFight** [comment]
@aralper looking to your [address in block-explorer](https://fuellabs.github.io/block-explorer-v2/beta-3/#/address/fuel1vjuj3rs7940pmpgx70w22t8c78w4cjpkuhgxn4ef8szuutmkq4kq569mwq)

I see you don't have 0.5ETH, instead have 0.999999987 which is probably because you faucet 2 times, and spent in some transactions.

anyway, balance shown is not calculated in wallet level, it comes from this query for example:
```
query balance {
  balance(owner: "0x64b9288e1e2d5e1d8506f3dca52cf8f1dd5c4836e5d069d7293c05ce2f76056c", assetId: "0x0000000000000000000000000000000000000000000000000000000000000000") {
    owner
    amount
    assetId
  }
}
```

depending on how your transaction is mounted, you might not spend ETH.

Wallet is just a way to approve it, but transaction is provided by the dapp (thunder in this case). You could report this error to thunder team if it's still reproducible, but yeah the transactions I see in block-explorer doesn't seem to be spending ETH, you probably spent in fees only

**Comment by aralper** [comment]
thnks for answer. ı write already thunder team.
________________________________
Gönderen: Luiz Gomes - LuizAsFight.eth ***@***.***>
Gönderildi: 20 Nisan 2023 Perşembe 00:53
Kime: FuelLabs/fuels-wallet ***@***.***>
Bilgi: aralper ***@***.***>; Mention ***@***.***>
Konu: Re: [FuelLabs/fuels-wallet] no decrease in balance (Issue #623)


@aralper<https://github.com/aralper> looking to your address in block-explorer<https://fuellabs.github.io/block-explorer-v2/beta-3/#/address/fuel1vjuj3rs7940pmpgx70w22t8c78w4cjpkuhgxn4ef8szuutmkq4kq569mwq>

I see you don't have 0.5ETH, instead have 0.999999987 which is probably because you faucet 2 times, and spent in some transactions.

anyway, balance shown is not calculated in wallet level, it comes from this query for example:

query balance {
  balance(owner: "0x64b9288e1e2d5e1d8506f3dca52cf8f1dd5c4836e5d069d7293c05ce2f76056c", assetId: "0x0000000000000000000000000000000000000000000000000000000000000000") {
    owner
    amount
    assetId
  }
}


depending on how your transaction is mounted, you might not spend ETH.

Wallet is just a way to approve it, but transaction is provided by the dapp (thunder in this case). You could report this error to thunder team if it's still reproducible, but yeah the transactions I see in block-explorer doesn't seem to be spending ETH, you probably spent in fees only
