### ISSUE TITLE
transferring assets just hangs

### ISSUE THREAD

**Issue by kayoam7** [FuelLabs/fuels-wallet#634]
### What version of Wallet are you using?

testnet beta 3

### What is happening?

on the how to use page, all steps work, except the transfer assets part of the testnet. at this juncture it just hangs and doesnt do anything, so im not sure its a bug on your side, or due to brave browser which seems to have some extension issues at the moment with phantom wallet and others(which i have disabled)

### steps to reproduce

transfer assets should work seamlessly,  

### How it should behave?

should transfer instantly.

### What os are you seeing the problem on?

Mac/Apple Desktop

### What browser?

Brave

### What is your browser version?

1.49.120

**Comment by luizstacio** [comment]
@kayoam7, thanks for the report. In the past weeks, our network was unstable, causing transactions to be very slow and not finishing the execution, making issues like this happen. This should be solved now.

Please let us know if the issue is still happening then we can re-open the issue and work on it.
