### ISSUE TITLE
swayswap can't work

### ISSUE THREAD

**Issue by zhengkai88** [FuelLabs/fuels-wallet#636]
### What version of Wallet are you using?

0.7.1

### What is happening?

![福昕截屏20230326182844908](https://user-images.githubusercontent.com/116860205/227770101-24548d5a-4864-43ef-b5a4-6cc286bd4a5a.PNG)

### steps to reproduce

can't linked say error

### How it should behave?

relsove it

### What os are you seeing the problem on?

Windows Desktop

### What browser?

Chrome

### What is your browser version?

 111.0.5563.111

**Comment by luizstacio** [comment]
@zhengkai88, thanks for the report. These errors in the captcha can be due to the browser or network. When it happens, you should retry it. We released a fix on swayswap a couple of days ago to refresh the captcha automatically without the need to refresh the page.

Please let me know if you still have issues with the faucet so we can re-open the issue and investigate more on it.
