### ISSUE TITLE
Transfering Assets

### ISSUE THREAD

**Issue by YellowRedTrader** [FuelLabs/fuels-wallet#648]
### What version of Wallet are you using?

Testnet Beta 3 Version: 0.7.1

### What is happening?

Hi 

The project will contribute to the ecosystem.
Congratulations to the team
The transfer did not take place

![fuel 2](https://user-images.githubusercontent.com/128170883/228605691-44f52254-4c57-4167-af00-f8bc4caa0024.JPG)
![fuel 1](https://user-images.githubusercontent.com/128170883/228605697-90b4a774-3664-4a23-897c-9418317d05c3.JPG)

### steps to reproduce

I tried 3-4 times. Errors continue

### How it should behave?

You should speed up the network
The number of test tokens may increase

### What os are you seeing the problem on?

Windows Desktop

### What browser?

Chrome

### What is your browser version?

Version 111.0.5563.112 (Official Build) (64-bit)

**Comment by YellowRedTrader** [comment]
fuel1ny94rplukujhrrzl347gknu20gndvhwp7ul648rdyeltsuwwkrds5x3jjh

**Comment by luizstacio** [comment]
@YellowRedTrader, thanks for the comment and the report;

1. About the assets, if you had added the asset before it failed, this is expected behavior. Let us know if you don't have the asset added to the wallet. You can check it by going to `sidebar -> settings -> assets`.
2. About the network speed,  In the past weeks, our network was unstable, causing transactions to be very slow and not finishing the execution, breaking the flow with errors like this as the network responded with 500 errors. This should be solved now.

Please let me know if the issues persist than we can re-open the issue and work on it.
