### ISSUE TITLE
Account creation

### ISSUE THREAD

**Issue by danevqq** [FuelLabs/fuels-wallet#707]
### What version of Wallet are you using?

Version: 0.7.2

### What is happening?

Incorrect creation of a new account / incorrect wallet recovery

### steps to reproduce

I created a second account in the wallet, requested test tokens for it, and made a couple of transactions between accounts. I reset the wallet through the settings and restored it through the same seed-phrase. After that my accounts settings reset, and I decided to add a new account again (NOT IMPORT BY PRIVATE KEY), but instead of the new account appeared my old account that I created before resetting the wallet with the same balance, but a different name. 

### How it should behave?

Either a new account must be created when creating a new account, or all previously created accounts must be imported automatically when the wallet is restored via the seed-phrase

### What os are you seeing the problem on?

Mac/Apple Desktop

### What browser?

Brave

### What is your browser version?

Version 1.50.114

**Comment by danevqq** [comment]
Just in case my Fuel address:
fuel1hv0vcv8m4q3ek5v0tgjcj6vgudxt7c0ghqgagz37j7rs7s4qggdqqzjgwt

**Comment by luizstacio** [comment]
@danevqq thanks for the report. This is expected behavior as the seed phrase uses HDWallet, and the sequence of accounts created will always be the same.  As the number of accounts you have is not present on the seed phrase itself, We can't import all previous accounts created.

Our idea for the future is to scan all accounts and enable the users to import the previous accounts with some TXs history / Balance. This is not a short-term priority on the Walle and contributions will be very welcome. You can also track when this is implemented here #713.
