### ISSUE TITLE
Create component that switches between bech32 and HEX address

### ISSUE THREAD

**Issue by luizstacio** [FuelLabs/fuels-wallet#800]
Enable users to visualize and copy the HEX value of a bech32 address directly on the Wallet.

Todo;
- Change the tooltip that currently shows the complete address to a help instruction: "Show HEX address";
- The help text should change between `HEX` and `fuel` depending on what is being shown;
- Add an action for the address to switch between the two formats to display the address;
- When clicking on the copy button, it should copy the address in the current format displayed.

**Comment by diyahir** [comment]
Since there's a one-to-one mapping, then let's just show users what they are used to...no need to introduce another address adding to the confusion 

I think bech32 is a mistake, even if there's an option to switch seamlessly between, this sounds over-engineered

So users will now have bech32, hex, fuel naming system name

**Comment by PaulRBerg** [comment]
This is an important missing feature.

I'm trying to figure out how to obtain the appropriate hex address for making GraphQL queries:

https://forum.fuel.network/t/fuel-address-format-in-graphql-queries/3067

**Comment by luizstacio** [comment]
closed by: https://github.com/FuelLabs/fuels-wallet/pull/874
